export const Modals = {
    MOD_CHANGELOG: 'MOD_CHANGELOG',
    MAC_UPDATE_DIALOG: 'MAC_UPDATE_DIALOG',
    LINUX_ASAR_PATH: 'LINUX_ASAR_PATH',
    APP_UPDATE_DIALOG: 'APP_UPDATE_DIALOG',
    PULSE_SYNC_DIALOG: 'PULSE_SYNC_DIALOG',
    YANDEX_MUSIC_UPDATE_DIALOG: 'YANDEX_MUSIC_UPDATE_DIALOG',
    PREMIUM_PROMO: 'PREMIUM_PROMO',
    PREMIUM_UNLOCKED: 'PREMIUM_UNLOCKED',
    MAC_PERMISSIONS_MODAL: 'MAC_PERMISSIONS_MODAL',
} as const
