import { Track } from '../interfaces/track.interface'

const TrackInitials: Track = {
    sourceType: '',
    currentDevice: {
        info: {
            device_id: '',
            title: '',
            type: null,
            app_name: '',
            app_version: '',
        },
        volume: 0,
        capabilities: {
            can_be_player: false,
            can_be_remote_controller: false,
            volume_granularity: 0,
        },
        session: { id: '' },
        is_offline: false,
        volume_info: {
            volume: 0,
            version: {
                device_id: '',
                version: '',
                timestamp_ms: '',
            },
        },
    },
    downloadInfo: {
        trackId: '',
        quality: '',
        codec: '',
        bitrate: 0,
        transport: '',
        key: '',
        size: 0,
        gain: false,
        urls: [],
        url: '',
        realId: '',
    },
    isPlaying: false,
    canMoveBackward: false,
    canMoveForward: false,
    status: 'paused',
    ynisonProgress: 0,
    progress: {
        duration: 0,
        loaded: 0,
        position: 0,
        played: 0,
    },
    availableActions: {
        moveBackward: false,
        moveForward: false,
        repeat: false,
        shuffle: false,
        speed: false,
    },
    actionsStore: {
        repeat: '',
        shuffle: false,
        isLiked: false,
        isDisliked: false,
    },
    id: '',
    realId: '',
    title: '',
    major: { id: 0, name: '' },
    available: false,
    availableForPremiumUsers: false,
    availableFullWithoutPermission: false,
    availableForOptions: [],
    disclaimers: [],
    storageDir: '',
    durationMs: 0,
    fileSize: 0,
    r128: { i: 0, tp: 0 },
    fade: {
        inStart: 0,
        inStop: 0,
        outStart: 0,
        outStop: 0,
    },
    previewDurationMs: 0,
    artists: [
        {
            id: 0,
            name: '',
            various: false,
            composer: false,
            available: false,
            cover: { type: '', uri: '', prefix: '' },
            genres: [],
            disclaimers: [],
        },
    ],
    albums: [
        {
            id: 0,
            title: '',
            metaType: '',
            version: '',
            year: 0,
            releaseDate: '',
            coverUri: '',
            ogImage: '',
            genre: '',
            trackCount: 0,
            likesCount: 0,
            recent: false,
            veryImportant: false,
            artists: [
                {
                    id: 0,
                    name: '',
                    various: false,
                    composer: false,
                    available: false,
                    cover: { type: '', uri: '', prefix: '' },
                    genres: [],
                    disclaimers: [],
                },
            ],
            labels: [{ id: 0, name: '' }],
            available: false,
            availableForPremiumUsers: false,
            availableForOptions: [],
            availableForMobile: false,
            availablePartially: false,
            bests: [],
            disclaimers: [],
            listeningFinished: false,
            trackPosition: { volume: 0, index: 0 },
        },
    ],
    albumArt: '',
    derivedColors: {
        average: '',
        waveText: '',
        miniPlayer: '',
        accent: '',
    },
    ogImage: '',
    url: '',
    lyricsAvailable: false,
    type: '',
    rememberPosition: false,
    trackSharingFlag: '',
    lyricsInfo: {
        hasAvailableSyncLyrics: false,
        hasAvailableTextLyrics: false,
    },
    trackSource: '',
    specialAudioResources: [],
}

export default TrackInitials
