const Events = {
    DISCORDRPC_SETSTATE: 'DISCORDRPC_SETSTATE',
    DISCORDRPC_DISCORDRPC: 'DISCORDRPC_DISCORDRPC',
    DISCORDRPC_RESET_ACTIVITY: 'DISCORDRPC_RESET_ACTIVITY',
    DISCORDRPC_CLEARSTATE: 'DISCORDRPC_CLEARSTATE',

    WEBSOCKET_START: 'WEBSOCKET_START',
    WEBSOCKET_STOP: 'WEBSOCKET_STOP',
    WEBSOCKET_RESTART: 'WEBSOCKET_RESTART',

    REFRESH_MOD_INFO: 'REFRESH_MOD_INFO',
    REFRESH_EXTENSIONS: 'REFRESH_EXTENSIONS',

    DOWNLOAD_OBS_WIDGET: 'DOWNLOAD_OBS_WIDGET',
    REMOVE_OBS_WIDGET: 'REMOVE_OBS_WIDGET',
    CHECK_OBS_WIDGET_INSTALLED: 'CHECK_OBS_WIDGET_INSTALLED',
    GET_OBS_WIDGET_PATH: 'GET_OBS_WIDGET_PATH',

    GET_TRACK_INFO: 'GET_TRACK_INFO',

    INSTALL_MOD: 'INSTALL_MOD',
    REMOVE_MOD: 'REMOVE_MOD',

    FILE_EVENT: 'FILE_EVENT',
    DELETE_ADDON_DIRECTORY: 'DELETE_ADDON_DIRECTORY',

    THEME_CHANGED: 'THEME_CHANGED',

    ELECTRON_WINDOW_MINIMIZE: 'ELECTRON_WINDOW_MINIMIZE',
    ELECTRON_WINDOW_EXIT: 'ELECTRON_WINDOW_EXIT',
    ELECTRON_WINDOW_MAXIMIZE: 'ELECTRON_WINDOW_MAXIMIZE',
    ELECTRON_WINDOW_CLOSE: 'ELECTRON_WINDOW_CLOSE',

    ELECTRON_SETTINGS_MINIMIZE: 'ELECTRON_SETTINGS_MINIMIZE',
    ELECTRON_SETTINGS_EXIT: 'ELECTRON_SETTINGS_EXIT',

    OPEN_DEVTOOLS: 'OPEN_DEVTOOLS',
    OPEN_SETTINGS: 'OPEN_SETTINGS',

    GET_APP_VERSION: 'GET_APP_VERSION',
    GET_CORE_VERSION: 'GET_CORE_VERSION',
    GET_YM_VERSION: 'GET_YM_VERSION',

    GET_USER_DATA: 'GET_USER_DATA',
    GET_APP_DATA: 'GET_APP_DATA',
    GET_APP_PATHS: 'GET_APP_PATHS',
    GET_ADDON_PATHS: 'GET_ADDON_PATHS',

    READ_LOGS: 'READ_LOGS',
    CLEAR_LOGS: 'CLEAR_LOGS',
    OPEN_LOGS_DIR: 'OPEN_LOGS_DIR',
    OPEN_APP_DIR: 'OPEN_APP_DIR',
    OPEN_ADDONS_DIR: 'OPEN_ADDONS_DIR',
    OPEN_FFMPEG_DIR: 'OPEN_FFMPEG_DIR',
    OPEN_DOWNLOADS_DIR: 'OPEN_DOWNLOADS_DIR',

    OPEN_EXTERNAL_URL: 'OPEN_EXTERNAL_URL',

    SHELL_SHOW_ITEM_IN_FOLDER: 'SHELL_SHOW_ITEM_IN_FOLDER',

    FFMPEG_DOWNLOAD: 'FFMPEG_DOWNLOAD',
    FFMPEG_CANCEL_DOWNLOAD: 'FFMPEG_CANCEL_DOWNLOAD',
    FFMPEG_CHECK_INSTALLED: 'FFMPEG_CHECK_INSTALLED',
    FFMPEG_GET_PATHS: 'FFMPEG_GET_PATHS',
    FFMPEG_SET_PATHS: 'FFMPEG_SET_PATHS',
    FFMPEG_RESET_PATHS: 'FFMPEG_RESET_PATHS',
    FFMPEG_TEST_RUN: 'FFMPEG_TEST_RUN',

    DOWNLOAD_MUSIC_EXECUTE: 'DOWNLOAD_MUSIC_EXECUTE',
    DOWNLOAD_MUSIC_CANCEL: 'DOWNLOAD_MUSIC_CANCEL',
    DOWNLOAD_MUSIC_OPEN_FOLDER: 'DOWNLOAD_MUSIC_OPEN_FOLDER',

    GET_SETTINGS: 'GET_SETTINGS',
    SET_SETTINGS: 'SET_SETTINGS',
    RESET_SETTINGS: 'RESET_SETTINGS',
    TOGGLE_START_ON_BOOT: 'TOGGLE_START_ON_BOOT',

    CHECK_FOR_UPDATES: 'CHECK_FOR_UPDATES',
    QUIT_AND_INSTALL: 'QUIT_AND_INSTALL',
    UPDATER_SET_AUTO: 'UPDATER_SET_AUTO',
    UPDATER_GET_AUTO: 'UPDATER_GET_AUTO',

    MOD_MANAGER_INSTALL: 'MOD_MANAGER_INSTALL',
    MOD_MANAGER_REMOVE: 'MOD_MANAGER_REMOVE',
    MOD_MANAGER_ENABLE: 'MOD_MANAGER_ENABLE',
    MOD_MANAGER_DISABLE: 'MOD_MANAGER_DISABLE',
    MOD_MANAGER_LIST: 'MOD_MANAGER_LIST',
    MOD_MANAGER_OPEN_DIR: 'MOD_MANAGER_OPEN_DIR',

    EXTENSION_MANAGER_CREATE: 'EXTENSION_MANAGER_CREATE',
    EXTENSION_MANAGER_EXPORT: 'EXTENSION_MANAGER_EXPORT',
    EXTENSION_MANAGER_LIST: 'EXTENSION_MANAGER_LIST',
    EXTENSION_MANAGER_OPEN_DIR: 'EXTENSION_MANAGER_OPEN_DIR',

    RENDERER_LOG: 'RENDERER_LOG',
    LOG_ERROR: 'LOG_ERROR',

    SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
    NEED_MODAL_UPDATE: 'NEED_MODAL_UPDATE',
    GET_LOG_ARCHIVE: 'GET_LOG_ARCHIVE',
    CHECK_SLEEP_MODE: 'CHECK_SLEEP_MODE',

    GET_ADDONS: 'GET_ADDONS',
    OPEN_SETTINGS_WINDOW: 'OPEN_SETTINGS_WINDOW',
    CREATE_NEW_EXTENSION: 'CREATE_NEW_EXTENSION',
    EXPORT_ADDON: 'EXPORT_ADDON',

    ELECTRON_SETTINGS_MAXIMIZE: 'ELECTRON_SETTINGS_MAXIMIZE',
    ELECTRON_SETTINGS_CLOSE: 'ELECTRON_SETTINGS_CLOSE',

    ELECTRON_ISDEV: 'ELECTRON_ISDEV',
    ELECTRON_ISMAC: 'ELECTRON_ISMAC',
    ELECTRON_ISLINUX: 'ELECTRON_ISLINUX',
    ELECTRON_MAC: 'ELECTRON_MAC',

    GET_VERSION: 'GET_VERSION',
    GET_LAST_BRANCH: 'GET_LAST_BRANCH',

    ELECTRON_STORE_GET: 'ELECTRON_STORE_GET',
    ELECTRON_STORE_SET: 'ELECTRON_STORE_SET',
    ELECTRON_STORE_DELETE: 'ELECTRON_STORE_DELETE',

    GET_SYSTEM_INFO: 'GET_SYSTEM_INFO',
    UI_READY: 'UI_READY',

    OPEN_EXTERNAL: 'OPEN_EXTERNAL',
    OPEN_FILE: 'OPEN_FILE',
    OPEN_PATH: 'OPEN_PATH',
    DIALOG_OPEN_FILE: 'DIALOG_OPEN_FILE',
    DIALOG_OPEN_DIRECTORY: 'DIALOG_OPEN_DIRECTORY',
    DIALOG_SAVE_FILE: 'DIALOG_SAVE_FILE',
    FILE_AS_DATA_URL: 'FILE_AS_DATA_URL',
    DIALOG_OPEN_FILE_METADATA: 'DIALOG_OPEN_FILE_METADATA',

    DOWNLOAD_YANDEX_MUSIC: 'DOWNLOAD_YANDEX_MUSIC',

    GET_MUSIC_DEVICE: 'GET_MUSIC_DEVICE',
    AUTO_START_APP: 'AUTO_START_APP',
    GET_MUSIC_STATUS: 'GET_MUSIC_STATUS',
    GET_MUSIC_VERSION: 'GET_MUSIC_VERSION',
    CHECK_MUSIC_INSTALL: 'CHECK_MUSIC_INSTALL',

    UPDATE_INSTALL: 'UPDATE_INSTALL',
    CHECK_UPDATE: 'CHECK_UPDATE',
    UPDATER_START: 'UPDATER_START',

    UPDATE_RPC_SETTINGS: 'UPDATE_RPC_SETTINGS',
    AUTH_STATUS: 'AUTH_STATUS',

    SHOW_ADD_PULSESYNC_DIALOG: 'SHOW_ADD_PULSESYNC_DIALOG',
    PULSESYNC_ADD_ENTRY: 'PULSESYNC_ADD_ENTRY',
    PULSESYNC_DISMISS: 'PULSESYNC_DISMISS',

    CLEAR_MOD_CACHE: 'CLEAR_MOD_CACHE',

} as const

export default Events
export type MainEvent = (typeof Events)[keyof typeof Events]
