const Events = {
    OPEN_ADDON: 'OPEN_ADDON',
    CLIENT_READY: 'CLIENT_READY',
    AUTH_BANNED: 'AUTH_BANNED',

    TRACK_INFO: 'TRACK_INFO',
    SEND_TRACK: 'SEND_TRACK',
    AUTH_SUCCESS: 'AUTH_SUCCESS',

    CHECK_MOD_UPDATE: 'CHECK_MOD_UPDATE',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',

    DOWNLOAD_PROGRESS: 'DOWNLOAD_PROGRESS',
    DOWNLOAD_SUCCESS: 'DOWNLOAD_SUCCESS',
    DOWNLOAD_FAILURE: 'DOWNLOAD_FAILURE',
    REMOVE_MOD_SUCCESS: 'REMOVE_MOD_SUCCESS',
    REMOVE_MOD_FAILURE: 'REMOVE_MOD_FAILURE',

    DOWNLOAD_OBS_WIDGET_SUCCESS: 'DOWNLOAD_OBS_WIDGET_SUCCESS',
    DOWNLOAD_OBS_WIDGET_FAILURE: 'DOWNLOAD_OBS_WIDGET_FAILURE',
    DOWNLOAD_OBS_WIDGET_PROGRESS: 'DOWNLOAD_OBS_WIDGET_PROGRESS',
    REMOVE_OBS_WIDGET_SUCCESS: 'REMOVE_OBS_WIDGET_SUCCESS',
    REMOVE_OBS_WIDGET_FAILURE: 'REMOVE_OBS_WIDGET_FAILURE',

    DOWNLOAD_UPDATE_PROGRESS: 'DOWNLOAD_UPDATE_PROGRESS',
    CHECK_UPDATE: 'CHECK_UPDATE',
    DOWNLOAD_UPDATE_FINISHED: 'DOWNLOAD_UPDATE_FINISHED',
    UPDATE_APP_DATA: 'UPDATE_APP_DATA',
    DOWNLOAD_UPDATE_FAILED: 'DOWNLOAD_UPDATE_FAILED',
    UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
    MAC_UPDATE_READY: 'MAC_UPDATE_READY',
    REQUEST_MAC_PERMISSIONS: 'REQUEST_MAC_PERMISSIONS',

    DOWNLOAD_MUSIC_PROGRESS: 'DOWNLOAD_MUSIC_PROGRESS',
    DOWNLOAD_MUSIC_FAILURE: 'DOWNLOAD_MUSIC_FAILURE',
    DOWNLOAD_MUSIC_EXECUTION_SUCCESS: 'DOWNLOAD_MUSIC_EXECUTION_SUCCESS',

    CHECK_FILE_EXISTS: 'CHECK_FILE_EXISTS',
    READ_FILE: 'READ_FILE',
    READ_FILE_BASE64: 'READ_FILE_BASE64',
    CREATE_CONFIG_FILE: 'CREATE_CONFIG_FILE',
    WRITE_FILE: 'WRITE_FILE',
    WRITE_FILE_BASE64: 'WRITE_FILE_BASE64',
    DELETE_FILE: 'DELETE_FILE',
    COPY_FILE: 'COPY_FILE',

    SHOW_MOD_MODAL: 'SHOW_MOD_MODAL',
    AS_DATA_URL: 'AS_DATA_URL',
    SHOW_ADD_PULSESYNC_DIALOG: 'SHOW_ADD_PULSESYNC_DIALOG',

    CLEAR_MOD_CACHE_SUCCESS: 'CLEAR_MOD_CACHE_SUCCESS',
    CLEAR_MOD_CACHE_FAILURE: 'CLEAR_MOD_CACHE_FAILURE',
    OPEN_MODAL: 'OPEN_MODAL',

    IS_PREMIUM_USER: 'IS_PREMIUM_USER',
    PREMIUM_CHECK_TOKEN: 'PREMIUM_CHECK_TOKEN',
} as const

export default Events
export type RendererEvent = (typeof Events)[keyof typeof Events]
